/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: jacobian_fcn.c
 *
 * MATLAB Coder version            : 5.3
 * C/C++ source code generated on  : 21-Jun-2022 12:59:19
 */

/* Include Files */
#include "jacobian_fcn.h"
#include <math.h>

/* Function Definitions */
/*
 * JACOBIAN_FCN
 *     Jacobi_camera = JACOBIAN_FCN(Q_1,Q_2,Q_3,Q_4,Q_5)
 *
 * Arguments    : double q_1
 *                double q_2
 *                double q_3
 *                double q_4
 *                double q_5
 *                double Jacobi_camera[36]
 * Return Type  : void
 */
void jacobian_fcn(double q_1, double q_2, double q_3, double q_4, double q_5,
                  double Jacobi_camera[36])
{
  double t12;
  double t13;
  double t16;
  double t17;
  double t18;
  double t19;
  double t2;
  double t22;
  double t26;
  double t27;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t35;
  double t36;
  double t4;
  double t5;
  double t50;
  double t50_tmp;
  double t52;
  double t6;
  double t66;
  double t68;
  double t7;
  double t73;
  double t74;
  double t8;
  double t83;
  double t9;
  double t90;
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     21-Jun-2022 12:53:05 */
  t2 = cos(q_1);
  t3 = cos(q_3);
  t4 = cos(q_5);
  t5 = sin(q_1);
  t6 = sin(q_3);
  t7 = sin(q_5);
  t8 = q_1 + q_5;
  t9 = (q_2 + q_3) + q_4;
  t12 = cos(t9);
  t13 = q_1 + t9;
  t17 = t8 + t9;
  t19 = q_1 + -q_5;
  t22 = t4 / 200.0;
  t26 = t9 + -q_1;
  t35 = -t8 + t9;
  t16 = cos(t13);
  t18 = sin(t13);
  t29 = cos(t26);
  t32 = -q_5 + t13;
  t33 = q_5 + t26;
  t34 = sin(t26);
  t27 = cos(q_2 + -1.5707963267948966);
  t13 = cos(q_4 + -1.5707963267948966);
  t30 = sin(q_2 + -1.5707963267948966);
  t31 = sin(q_4 + -1.5707963267948966);
  t36 = t27 * 0.3;
  t50_tmp = t7 * t13;
  t50 = t22 * t31 + t50_tmp * 3.061616997868383E-19;
  t26 = t7 * t31;
  t52 = t22 * t13 + -(t26 * 3.061616997868383E-19);
  t26 = (t26 / 200.0 + -(t4 * t13 * 3.061616997868383E-19)) + t13 * 0.1354;
  t13 = (t50_tmp / 200.0 + t4 * t31 * 3.061616997868383E-19) + -(t31 * 0.1354);
  t66 = t3 * t50 + t6 * t52;
  t73 = t3 * t26 + t6 * t13;
  t68 = t27 * t66;
  t74 = t3 * t13 + -(t6 * t26);
  t13 = t6 * 0.18 + t73;
  t26 = t3 * 0.18 + t74;
  t83 = t30 * t13;
  t52 = t6 * t50 - t3 * t52;
  t3 = t68 + -t30 * t52;
  t6 = t27 * t26;
  t90 = t27 * t73 + t30 * t74;
  t26 = t27 * t13 + t30 * t26;
  t13 = t30 * 0.3 + t26;
  t31 = t36 + (t6 + -t83);
  t50_tmp = t5 * t31;
  t50 = t2 * t13;
  Jacobi_camera[0] =
      (t2 * (t22 + 0.093500000000000014) + t50 * 6.123233995736766E-17) +
      t50_tmp;
  t13 *= t5;
  Jacobi_camera[1] =
      (t5 * (t22 + 0.093500000000000014) + t13 * 6.123233995736766E-17) +
      -t2 * t31;
  Jacobi_camera[2] = 0.0;
  Jacobi_camera[3] = t5;
  Jacobi_camera[4] = -t2;
  Jacobi_camera[5] = 6.123233995736766E-17;
  Jacobi_camera[6] = t50 + t50_tmp * 6.123233995736766E-17;
  Jacobi_camera[7] = t2 * t31 * -6.123233995736766E-17 + t13;
  Jacobi_camera[8] = (-t36 + t83) + -t6;
  Jacobi_camera[9] = t5;
  Jacobi_camera[10] = -t2;
  Jacobi_camera[11] = 6.123233995736766E-17;
  t50_tmp = t83 + -t6;
  Jacobi_camera[12] = t5 * t50_tmp * -6.123233995736766E-17 + t2 * t26;
  Jacobi_camera[13] = t2 * t50_tmp * 6.123233995736766E-17 + t5 * t26;
  Jacobi_camera[14] = t50_tmp;
  Jacobi_camera[15] = t5;
  Jacobi_camera[16] = -t2;
  Jacobi_camera[17] = 6.123233995736766E-17;
  t50_tmp = t30 * t73 - t27 * t74;
  Jacobi_camera[18] = t2 * t90 - t5 * t50_tmp * 6.123233995736766E-17;
  Jacobi_camera[19] = t5 * t90 + t2 * t50_tmp * 6.123233995736766E-17;
  Jacobi_camera[20] = t50_tmp;
  Jacobi_camera[21] = (t5 * 6.123233995736766E-17 - t18 * 0.5) - t34 * 0.5;
  Jacobi_camera[22] = (t2 * -6.123233995736766E-17 + t16 * 0.5) - t29 * 0.5;
  Jacobi_camera[23] = t12 + 3.749399456654644E-33;
  t50_tmp = t30 * t66 + t27 * t52;
  Jacobi_camera[24] =
      (t2 * t50_tmp - t5 * t7 / 200.0) + t5 * t3 * 6.123233995736766E-17;
  Jacobi_camera[25] =
      (t5 * t50_tmp + t2 * t7 / 200.0) - t2 * t3 * 6.123233995736766E-17;
  Jacobi_camera[26] = (t7 * -3.061616997868383E-19 - t68) + t30 * t52;
  Jacobi_camera[27] =
      (((((t5 * 3.749399456654644E-33 + t18 * -3.061616997868383E-17) +
          (t34 * -3.061616997868383E-17 + sin(t8) / 2.0)) +
         (sin(t17) * 0.25 + sin(t19) / 2.0)) +
        sin(t32) * -0.25) +
       sin(t33) * 0.25) +
      sin(t35) * -0.25;
  Jacobi_camera[28] =
      (((((t2 * -3.749399456654644E-33 + t16 * 3.061616997868383E-17) +
          (t29 * -3.061616997868383E-17 - cos(t8) / 2.0)) +
         (cos(t17) * -0.25 - cos(t19) / 2.0)) +
        cos(t32) * 0.25) +
       cos(t33) * 0.25) +
      cos(t35) * -0.25;
  Jacobi_camera[29] =
      (((t4 * 6.123233995736766E-17 + t12 * 6.123233995736766E-17) -
        cos(q_5 + t9) * 0.5) +
       cos(t9 + -q_5) * 0.5) +
      2.2958450216584679E-49;
  Jacobi_camera[30] = 0.0;
  Jacobi_camera[31] = 0.0;
  Jacobi_camera[32] = 0.0;
  Jacobi_camera[33] = 0.0;
  Jacobi_camera[34] = 0.0;
  Jacobi_camera[35] = 0.0;
}

/*
 * File trailer for jacobian_fcn.c
 *
 * [EOF]
 */
