function T_3 = T3(q_3)
%T3
%    T_3 = T3(Q_3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Jun-2022 13:05:36

t2 = cos(q_3);
t3 = sin(q_3);
T_3 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(-9.0./5.0e+1),t3.*(-9.0./5.0e+1),0.0,1.0],[4,4]);
