function T_4 = T4(q_4)
%T4
%    T_4 = T4(Q_4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Jun-2022 13:05:36

t2 = pi./2.0;
t3 = -t2;
t4 = q_4+t3;
t5 = cos(t4);
t6 = sin(t4);
T_4 = reshape([t5,t6,0.0,0.0,t6.*(-6.123233995736766e-17),t5.*6.123233995736766e-17,1.0,0.0,t6,-t5,6.123233995736766e-17,0.0,0.0,0.0,9.35e-2,1.0],[4,4]);
