function T_5 = T5(q_5)
%T5
%    T_5 = T5(Q_5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Jun-2022 13:05:36

t2 = cos(q_5);
t3 = sin(q_5);
T_5 = reshape([t2,t3,0.0,0.0,t3.*(-6.123233995736766e-17),t2.*6.123233995736766e-17,-1.0,0.0,-t3,t2,6.123233995736766e-17,0.0,0.0,0.0,2.0./2.5e+1,1.0],[4,4]);
