function T_6 = T6(q_6)
%T6
%    T_6 = T6(Q_6)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Jun-2022 13:05:36

t2 = cos(q_6);
t3 = sin(q_6);
T_6 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0./2.5e+1,1.0],[4,4]);
